package main

import (
	"net/http"
)

// ==================== 路由注册 ====================

func setupRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/", handleRoot)
	mux.HandleFunc("/popular", handlePopular)
	mux.HandleFunc("/ranking", handleRanking)
	mux.HandleFunc("/dynamic/feed", handleDynamicFeed)
	mux.HandleFunc("/search", handleSearch)
	mux.HandleFunc("/video/info", handleVideoInfo)
	mux.HandleFunc("/video/tags", handleVideoTags)
	mux.HandleFunc("/video/related", handleVideoRelated)
	mux.HandleFunc("/video/relation", handleVideoRelation)
	mux.HandleFunc("/video/playurl", handleVideoPlayurl)
	mux.HandleFunc("/video/merge", handleVideoMerge)
	mux.HandleFunc("/video/player/info", handleVideoPlayerInfo)
	mux.HandleFunc("/video/danmaku", handleVideoDanmaku)
	mux.HandleFunc("/video/danmaku/config", handleVideoDanmakuConfig)
	mux.HandleFunc("/video/comments", handleVideoComments)
	mux.HandleFunc("/video/comments/replies", handleVideoCommentsReplies)
	mux.HandleFunc("/comment/like/toggle", handleCommentLikeToggle)
	mux.HandleFunc("/video/subtitle/list", handleVideoSubtitleList)
	mux.HandleFunc("/video/subtitle/ass", handleVideoSubtitleASS)
	mux.HandleFunc("/video/subtitle/ass/file", handleVideoSubtitleASSFile)
	mux.HandleFunc("/user/info", handleUserInfo)
	mux.HandleFunc("/user/follow/toggle", handleUserFollowToggle)
	mux.HandleFunc("/user/videos", handleUserVideos)
	mux.HandleFunc("/user/search", handleUserSearch)
	mux.HandleFunc("/user/seasons", handleUserSeasons)
	mux.HandleFunc("/user/season/videos", handleUserSeasonVideos)
	mux.HandleFunc("/user/series/videos", handleUserSeriesVideos)
	mux.HandleFunc("/login/info", handleLoginInfo)
	mux.HandleFunc("/login/import", handleLoginImport)
	mux.HandleFunc("/logout", handleLogout)
	mux.HandleFunc("/hot/search", handleHotSearch)
	mux.HandleFunc("/recommend", handleRecommend)
	mux.HandleFunc("/history/recent", handleRecentHistory)
	mux.HandleFunc("/history/search", handleHistorySearch)
	mux.HandleFunc("/history/delete", handleHistoryDelete)
	mux.HandleFunc("/toview/list", handleToviewList)
	mux.HandleFunc("/toview/add", handleToviewAdd)
	mux.HandleFunc("/toview/del", handleToviewDel)
	mux.HandleFunc("/player/heartbeat", handlePlayerHeartbeat)
	mux.HandleFunc("/fav/folder/list", handleFavFolderList)
	mux.HandleFunc("/fav/resource/list", handleFavResourceList)
	mux.HandleFunc("/fav/status", handleFavStatus)
	mux.HandleFunc("/fav/toggle", handleFavToggle)
	mux.HandleFunc("/coin/status", handleCoinStatus)
	mux.HandleFunc("/coin/add", handleCoinAdd)
	mux.HandleFunc("/like/status", handleLikeStatus)
	mux.HandleFunc("/like/toggle", handleLikeToggle)
	mux.HandleFunc("/qrcode/generate", handleQrcodeGenerate)
	mux.HandleFunc("/qrcode/poll", handleQrcodePoll)
}
